version: '3.1'

services:

  wnotes-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wnotes_userk
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wnotes_db
    ports:
      - 3306:3306


  wnotes-adminer:
    image: adminer
    ports:
      - 8080:8080
