
CREATE TABLE Note (
	id 					int AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title 			VARCHAR(80) NOT NULL,
	content 		TEXT NOT NULL,
	created_at 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
